### ISSUE TITLE
[Feature]: Plot the graph

### ISSUE THREAD

**Issue by Dev7g** [OPCODE-Open-Spring-Fest/Accommodating-Insights#1]
How does the price of listings correlate with the number of reviews they receive?

plot a graph (a suitable one) with 'number_of_reviews' on the x-axis and 'price' on the y-axis.

### Observations:

* Examine the graph plot to identify any discernible patterns or trends.
* Analyze the relationship between price and the number of reviews:
       * Are higher-priced listings associated with more reviews, or vice versa?
       * Is there a correlation between price and the number of reviews?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@Dev7g Please assign me this issue

**Comment by Dev7g** [comment]
@xTwo56  You have been assigned this issue for 2 days.
