### ISSUE TITLE
[Feature]: Convert the non-numerical features into numerical 

### ISSUE THREAD

**Issue by Dev7g** [OPCODE-Open-Spring-Fest/Accommodating-Insights#11]
### So, what is it about?

How can I effectively encode non-numerical features like 'neighbourhood_group', 'neighbourhood', and 'room_type' into numerical representations, ensuring optimal utilization of this categorical data for analysis and modeling purposes while maintaining the meaningful distinctions inherent in each feature?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@Dev7g kindly assign me this issue

**Comment by Dev7g** [comment]
@xTwo56 you have been assigned this issue for 2 days

**Comment by Dev7g** [comment]
reassigning this issue @xTwo56
