### ISSUE TITLE
[Feature]: Correlation Analysis 

### ISSUE THREAD

**Issue by Dev7g** [OPCODE-Open-Spring-Fest/Accommodating-Insights#12]
### So, what is it about?

How can we comprehensively analyze the correlations between features within our dataset, discerning which features exhibit significant correlations and potentially uncovering underlying relationships or dependencies? Furthermore, could we visualize this analysis using a heatmap to provide a clear and intuitive representation of the correlations, thereby identifying clusters of correlated features for further investigation and potential feature engineering?

Give the observation made from the heatmap also.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@Dev7g Kindly assign me this issue

**Comment by Dev7g** [comment]
okay @xTwo56  You have been assigned this issue for 2 days.

**Comment by xTwo56** [comment]
@Dev7g Please re-assign

**Comment by ritikgupta65** [comment]
@Dev7g kindly assign this issue to me

**Comment by Dev7g** [comment]
okay @ritikgupta65 you have been assigned this issue for 2 days.

**Comment by Dev7g** [comment]
@xTwo56 you have been assigned this issue for 48 hours.
