### ISSUE TITLE
[Feature]: Logarithmic Transformation

### ISSUE THREAD

**Issue by Dev7g** [OPCODE-Open-Spring-Fest/Accommodating-Insights#2]
### So, what is it about?

What is the distribution of logarithmically transformed prices (price_log) for listings, and how does it compare to a normal distribution?

### Logarithmic Transformation:

Take the logarithmic transformation of the 'price' column and add it as a new column named 'price_log' to the dataframe.

* Plot a histogram or kernel density estimate (KDE) plot to visualize the distribution of 'price_log'.
* Overlay a normal distribution curve on the plot to compare it with the observed distribution.

### Observations:

* Analyze the plot to assess the similarity between the distribution of 'price_log' and a normal distribution.
* Determine if the logarithmically transformed prices exhibit characteristics of normality, such as symmetry and peakedness.
* Consider any deviations from normality and their implications for statistical analysis or modeling.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
Can I have this assignment

**Comment by Dev7g** [comment]
okay , assigning you this issue for 2 days @xTwo56
