### ISSUE TITLE
[Feature]: Fill the missing Values 

### ISSUE THREAD

**Issue by Dev7g** [OPCODE-Open-Spring-Fest/Accommodating-Insights#3]
### So, what is it about?

What is the most effective method for filling missing values in the 'reviews_per_month' column of the dataset, and how does it impact the distribution of reviews per month?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@Dev7g Can I have this assignment

**Comment by Dev7g** [comment]
sure @xTwo56

**Comment by Samriddhi2711** [comment]
@Dev7g please assign this task to me.

**Comment by shreya0415** [comment]
@Dev7g please assign this task to me.
